### ISSUE TITLE
input-line-separator method removed from rakudo

### ISSUE THREAD

**Issue by nxadm** [retupmoca/P6-Net-SMTP#10]
Hi, 

The input-line-separator method was removed from rakudo on the latest pre-christmas refactoring. Maybe the nl-in IO property could be a dropped in replacement (I tries changing the code, but the original didin't work for me in the first place).

Thank you,

Claudio

$ ./test.p6 
Method 'input-line-separator' not found for invocant of class 'IO::Socket::INET+{Net::SMTP::debug-connection}'
  in method new at /opt/ccis/usr/rakudobrew/moar-nom/install/share/perl6/site/sources/09694500870AE5685682D8A9159E8F9A573F5F9D line 34
  in method start at /opt/ccis/usr/rakudobrew/moar-nom/install/share/perl6/site/sources/83B00E9266D7FB7F7F51B8B95E7652984DA76406 line 55
  in method new at /opt/ccis/usr/rakudobrew/moar-nom/install/share/perl6/site/sources/09694500870AE5685682D8A9159E8F9A573F5F9D line 38
  in block <unit> at ./test.p6 line 6

$ cat test.p6 
#!/usr/bin/env perl6
use v6;
use Net::SMTP;

#simple interface
my $client = Net::SMTP.new(:server("localhost"),:debug);
$client.send('ccis@icts.kuleuven.be', 'claudio@kuleuven.be', "Subject:Test\n", "\n", "Body");
$client.quit;

**Comment by jonathanstowe** [comment]
Hi,
this will be fixed by #11 when it gets merged.
