### ISSUE TITLE
RFE: attachments

### ISSUE THREAD

**Issue by ToddAndMargo** [retupmoca/P6-Net-SMTP#14]
Request for Enhancement:

Would you please consider adding the ability to use attachments with this module?

Many thanks, -T

**Comment by retupmoca** [comment]
Attachments should pass through this module without any problems, although the Net::SMTP module is not responsible for creating the correct MIME structure to create a message with an attachment.

My process to create an attachment would be to create a message containing the body + attachment with Email::MIME, and then pass that message object through Net::SMTP. Is this (or a similar) flow not working?

**Comment by ToddAndMargo** [comment]
Hi Retupmoca,
Creating a MIME64 attachment, figuring out all the headers, is beyond my ability as a programmer.  I also can not find any legible documentation that I can understand to manually attach a document.  This is why I would like to have this functionality built in to your module.  Somewhere is Perl 5 land, one of the smtp modules will do this for you.  (I could always use Inline::Perl5, but I can not ever get it to install on certain machines, not to mention it is flaky.)  My immediate need is the ability to attach a tar ball.  I would sincerely appreciate you building it into your module, especially if it is as easy as you say.
Many thanks,
-T

**Comment by ToddAndMargo** [comment]
Fedora Core 25 ,x64

Okay, to add insult to injury.  There is a the Perl5 modules that has attachment capability (Email::Simple).   I just found out the hard way that if I place the following
     use Inline::Perl5;
     use Email::Simple:from<Perl5>;

lines in my program, my program will run perfectly from the command line, but when run from /etc/crontab (where it needs to be run), my program will just disappear.

Mind you I actually did not use this code, I had just pre-placed these lines and had forgotten to comment them out until I actually used them.    It was a hair puller to figure out.  (Commented out, my program runs perfectly from cron.)

Please, please, please, we really need attachment capability built in!
-T

**Comment by timo** [comment]
@ToddAndMargo here's how to create an email with attachments:

```use Email::MIME;

my $image = "P5\n64 64\n255\n".encode("utf8") ~ Buf[int8].new(
    do for -32..^32 X -32..^32 -> ($x, $y) {
        255 - (sqrt($x ** 2 + $y ** 2) * 4 % 255).ceiling
    });

my $email = Email::MIME.create(
    header-str => [from => "ToddAndMargo@zoho.com",
                   to => "timo@wakelift.de",
                   subject => "Check out my fantastic attachment!"],
    parts => [
        Email::MIME.create(
            header => [ content-transfer-encoding => "quoted-printable" ],
            attributes => [ content-type => "text/plain", charset => "utf8" ],
            body-str => "Hello Todd, check out this räd attachment!")
       ,Email::MIME.create(
            header => [ "Content-Transfer-Encoding" => "base64" ],
            attributes => [ content-type => "image/x-portable-greymap",
                            disposition => "attachment" ],
            body => $image
            )
    ]);

say $email.as-string;
```

it has a plain text body (including an utf8 character that gets encoded with quoted-printable) and it has an image attachment (a portable greymap that is created as a Buf, to simulate any attachments you would slurp as binary rather than encoded as a string).

It has the to and from headers in the Email::MIME object and it is part of the resulting text, so you can just feed that Net::SMTP's send method that only takes the message.

This relies on retupmoca/p6-Email-MIME#5 getting merged first.

**Comment by ToddAndMargo** [comment]
On 07/08/2017 02:58 AM, timo wrote:
> @ToddAndMargo <https://github.com/toddandmargo> here's how to create an 
> email with attachments:
> 
> my $image = "P5\n64 64\n255\n".encode("utf8") ~ Buf[int8].new( do for 
> -32..^32 X -32..^32 -> ($x, $y) { 255 - (sqrt($x ** 2 + $y ** 2) * 4 % 
> 255).ceiling });|

Hi Timo,

I am confused as to how I would add the name of the file I want to
attach to this line.  I am not sure what is your demonstration
of an attachment and where the attachment goes.  And I do not
know what is part of adding a file name.

I am confused.  :'(

-T




-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Computers are like air conditioners.
They malfunction when you open windows
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by timo** [comment]
```perl6

# these lines create some random attachment file in a Buf.
# In your code you would have something more like
#
#  my $image = "my-attachment.png".IO.slurp(:bin);
#
my $image = "P5\n64 64\n255\n".encode("utf8") ~ Buf[int8].new(
    do for -32..^32 X -32..^32 -> ($x, $y) {
        255 - (sqrt($x ** 2 + $y ** 2) * 4 % 255).ceiling
    });

# Here is where we compose the email made of multiple parts.
# We have an "outer" Email::MIME that holds the To, From, and
# Subject header and is responsible for making multiple parts
# "work" so that an email program can understand it.
my $email = Email::MIME.create(
    header-str => [From => "ToddAndMargo@zoho.com",
                   To => "timo@wakelift.de",
                   Subject => "Check out my fantastic attachment!"],
    # the parts array is where the magic happens
    parts => [
        # The first part is a simple plain-text message.
        Email::MIME.create(
            # a content-transfer-encoding is important when your encoding
            # (in this case utf8) can spit out bytes that are beyond ascii.
            # quoted-printable is a format that gives you mostly readable
            # data back (as you can see when the final line runs that prints
            # the resulting email.
            header => [ Content-Transfer-Cncoding => "quoted-printable" ],
            # the mime-type (aka content-type) for a plain text message is
            # just "text/plain". setting the charset to something valid is
            # important.
            attributes => [ Content-Type => "text/plain", charset => "utf8" ],
            # if we have just a string to put into this part, Email::MIME can
            # accept a perl6-string and it will encode it with the charset
            # we provided above and then further encode it with the
            # content-transfer-encoding we specified above.
            body-str => "Hello Todd, check out this räd attachment!")
        # Here is the second part, another Email::MIME object. This one
        # will contain our image (or whatever you slurped in as a binary
        # Blob with binary reading functions like .slurp(:bin) or .open(:bin) + read.
       ,Email::MIME.create(
            # base64 is a good encoding for when the data you're transmitting
            # doesn't have parts in it that are readable ASCII and just little bits
            # that are beyond ascii. In our case, around half the whole file are
            # unreadable as ascii and the other half is gibberish anyway.
            # This is true for many file formats that you might want to attach.
            header => [ "Content-Transfer-Encoding" => "base64" ],
            # Here we set the content-type to the MIME type corresponding
            # to a .pgm file (because that's what kind of image we created in
            # the code above).
            attributes => [ Content-Type => "image/x-portable-greymap",
            # the disposition attribute tells the receiving mail client what this
            # is supposed to be. in our case we want the content to appear in
            # a little box that will allow the user to "view" or "download".
            # that is what "attachment" is for. There is also "inline" which would
            # (depending on the receiving mail client of course) make the image
            # show up below our text part above.
            # This is where you can also put extra stuff like the filename
                            disposition => "attachment" ],
            # here we give the Blob (in my case Buf) to Email::MIME so it can
            # encode it (using the content-transfer-encoding) and put it into
            # the final message.
            body => $image
            )
    ]);

# Now that the email is composed with its two parts we can ask
# the object to stringify itself. This resulting string is ready to be
# sent with something like Net::SMTP.
say $email.as-string;
```

i added a whole lot of comments to the code. it looks like you only looked at the only completely un-important piece of my code, though?

Here's the output I get plus a bunch of comments so you can compare:

```
Date: Mon, 10 Jul 2017 13:37:33 Z   # just today's date, the Z stands for UTC i believe.
# the following line tells the email receiver that the mail is made up
# of multiple parts where each part has a different type ("mixed").
# The boundary is just a random string that is put between the
# parts so the receiving program can properly split it apart.
Content-Type: multipart/mixed; boundary="1499693890.68489.EFfc.989"
MIME-Version: 1.0
# the usual mail headers
from: ToddAndMargo@zoho.com
to: timo@wakelift.de
subject: Check out my fantastic attachment!

# The completely empty line above this line is what
# ends the headers section and starts the body section
# And the next line is the boundary for the multipart thing
--1499693890.68489.EFfc.989
# After the boundary there's headers again, just like
# in the beginning of the whole mail itself.
Date: Mon, 10 Jul 2017 13:37:33 Z
# Here's the content type and charset we used for
# the main body
Content-Type: text/plain; charset="utf8"
MIME-Version: 1.0
# And also the content-transfer-encoding
Content-Transfer-Encoding: quoted-printable

# Another empty line to transfer headers and body
# And here you can see the magic of quoted-printable.
# You can read everything except for the ä, because that
# is encoded as two bytes: 0xC3 and 0xA4
Hello Todd, check out this r=C3=A4d attachment!
# Here's the boundary again
--1499693890.68489.EFfc.989
Date: Mon, 10 Jul 2017 13:37:33 Z
# And this time the content type for our image.
Content-Type: image/x-portable-greymap
MIME-Version: 1.0
Content-Transfer-Encoding: base64
# Here you can see the "disposition" attribute sets
# the Content-Disposition header for us.
Content-Disposition: attachment

# After an empty line here comes the base64 encoded image.
# I cut almost all of it out because who likes to read base64.
UDUKNjQgNjQKMjU1CklMT1JUV1pcX2FjZWhqbG5vcXN0dnd4ent7fH1+fn5+f35+fn59fHt7enh3
dnRzcW9ubGpoZWNhX1xaV1RST0xMT1JVV1pdX2JkZmlrbW9xc3V2eHp7fH1+f4CBgYKCgoOCgoKB
[... many lines omitted ...]
UlVXWl1fYmRmaWttb3FzdXZ4ent8fX5/gIGBgoKCg4KCgoGBgH9+fXx7enh2dXNxb21raWZkYl9d
WldVUk8=
# One last time the boundary is put here
--1499693890.68489.EFfc.989--
# And the message ends
```

I hope that helps

**Comment by ToddAndMargo** [comment]
Hi Timo,

Part of the issue was that my firewall did not like my smtp port,
so I chose another one.

And I got it working as soon as I understood the headers.

Email::MIME.create(
     header => [ "Content-Transfer-Encoding" => "base64" ],
     attributes => [ content-type => "application/zip; name=$imagename",
                     disposition => "attachment" ],

And "stringy":
      $client.send( $from, @to, $email.as-string, :keep-going )

Thank you so much for sticking by me whist I fought through this.
I sincerely appreciate it.

-T


Here is my test code.  If it looks a little worky, it
is because I cut it out of the actual code and I
had to add a bunch of the supporting subs:

<code>
#!/usr/bin/env perl6

use strict;
use Net::SMTP;
use Email::MIME;
use Terminal::ANSIColor;  # color

my $Terminal = %*ENV<TERM>;
# print "\$Terminal = <$Terminal>\n";
( my $IAm =~ $?FILE ) ~~ s|.*"/"||;
my $ErrorCount = "0";  # 0 > is an error
my $Report;



sub PrintRed   ( $Str ) {
    if $Terminal ~~ /xterm || linux/ {
       print color('bold'), color('red'),   "$Str", color('reset');
    }
}
	
	
sub AddToReport ( $Str ) { $Report ~=  "$Str"; }

	
sub eMailReport () {
    # Reference: https://github.com/retupmoca/P6-Net-SMTP

    my $smtp     = "redacted";
    my $port     = 80;
    my $username = "redacted";
    my $password = "redacted";
    my $from     = "$username";
    my @to       = qw [ pci@storall.biz tmewell@zoho.com ];   # This is 
an array, not a string
    my $Subject  = "Subject: $IAm ERROR(s) = $ErrorCount";


    my $imagename = "logout.zip";
    my $imagepath = "/home/linuxutil";
    my $image     = "$imagepath/$imagename".IO.slurp(:bin);

    my $email = Email::MIME.create(
       header-str => [from => $from,
                      to => @to,
                      subject => $Subject ],
       parts => [
             Email::MIME.create(
                header => [ content-transfer-encoding => 
"quoted-printable" ],
                attributes => [ content-type => "text/plain", charset => 
"utf8" ],
                body-str => $Report ),

             Email::MIME.create(
               header => [ "Content-Transfer-Encoding" => "base64" ],
               # attributes => [ content-type => "image/x-portable-greymap",
               attributes => [ content-type => "application/zip; 
name=$imagename",
                             disposition => "attachment" ],
               body => $image
             )
     ]);

# say $email.as-string;
	
    if ( not my $client = Net::SMTP.new(:server( $smtp ), :port( $port 
), :debug( 0 ) ) ) {
	   $ErrorCount += 1;
	   PrintRed    ( "SMTP: unable to open $smtp\n" );
	   AddToReport ( "SMTP: unable to open $smtp\n" );
	   return;
	}
	
    if ( not $client.auth( $username, $password ) ) {
	   $ErrorCount += 1;
	   PrintRed    ( "SMTP: something is wrong with the username and/or 
password\n\n" );
	   AddToReport ( "SMTP: something is wrong with the username and/or 
password\n\n" );
       return;
	}
	
    if ( not $client.send( $from, @to, $email.as-string, :keep-going ) ) 
{ PrintRed "SMTP Error: Failed to send\n\n"; }

    $client.quit;
    # Seez!!!
}


$Report = "If this works,\nI am going to be surprised";
eMailReport;

</code>
